export default class ErrorMessage {
    public static readonly COMMON = {
        INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
        NOT_FOUND_API_ENDPOINT: 'NOT_FOUND_API_ENDPOINT',
        NOT_CONNECTION_SECRET_MANAGER: `NOT_CONNECTION_SECRET_MANAGER`
    };

    public static readonly AUTH = {
        NOT_FOUND_USER: 'NOT_FOUND_USER',
        ALREADY_EXIST_USER: 'ALREADY_EXIST_USER',
        ALREADY_EXIST_USERID: 'ALREADY_EXIST_USERID',
        ALREADY_EXIST_WELLCHECK_USER: 'ALREADY_EXIST_WELLCHECK_USER',
        INVALID_PASSWORD: 'INVALID_PASSWORD',
        NOT_FOUND_API_KEY: 'NOT_FOUND_API_KEY',
        INVALID_API_KEY: 'INVALID_API_KEY',
        USE_INTEGRATED_LOGIN_MUST_TRUE: 'USE_INTEGRATED_LOGIN_MUST_TRUE',
        INVALID_PHONE_NUMBER: 'INVALID_PHONE_NUMBER',
        IMPOSSIBLE_TO_SEND_CODE: 'IMPOSSIBLE_TO_SEND_CODE',
        FAIL_TO_SEND_CODE: 'FAIL_TO_SEND_CODE',
        ALREADY_USED_APPLE: 'ALREADY_USED_APPLE',
        ALREADY_USED_KAKAO: 'ALREADY_USED_KAKAO',
        ALREADY_USED_NAVER: 'ALREADY_USED_NAVER',
        INVALID_GOAL: 'INVALID_GOAL',
        NOT_FOUND_AUTH_CODE: 'NOT_FOUND_AUTH_CODE',
        TIME_OVER: 'TIME_OVER',
        RETRY_OVER: 'RETRY_OVER',
        INVALID_SOCIAL_CODE: 'INVALID_SOCIAL_CODE',
        ALREADY_USED_NORMAL: 'ALREADY_USED_NORMAL',
        NOT_FOUND_VERIFY: 'NOT_FOUND_VERIFY',
        INVALID_VERIFY_TYPE: 'INVALID_VERIFY_TYPE',
        INVALID_LOGIN_TYPE: 'INVALID_LOGIN_TYPE',
        NOT_VERIFIED_USER: 'NOT_VERIFIED_USER',
        INVALID_TOKEN_FORMAT: 'INVALID_TOKEN_FORMAT',
        NOT_ALLOWED_FOR_SOCIAL_USER: 'NOT_ALLOWED_FOR_SOCIAL_USER',
    };

    public static readonly VALIDATION = {
        IS_NOT_EMPTY: 'IS_NOT_EMPTY',
        MUST_BE_NUMBER: 'MUST_BE_NUMBER',
        MUST_BE_STRING: 'MUST_BE_STRING',
        NUMBER_LESS_THEN: 'NUMBER_LESS_THEN',
        NUMBER_GREATER_THEN: 'NUMBER_GREATER_THEN',
        STRING_LESS_THEN: 'STRING_LESS_THEN',
        STRING_GREATER_THEN: 'STRING_GREATER_THEN',
        ALREADY_NORMAL_TYPE: 'ALREADY_NORMAL_TYPE',
        LOGIN_TYPE_REQUIRED: 'LOGIN_TYPE_REQUIRED',
        TOKEN_REQUIRED: 'TOKEN_REQUIRED',
    };

    public static readonly SERVER = {
        WELL_CHECK_IS_NOT_JOINED: 'WELL_CHECK_IS_NOT_JOINED',
        WELL_CHECK_DIET_IS_NOT_JOINED: 'WELL_CHECK_DIET_IS_NOT_JOINED',
    };
}
